routes/web.php
<?php

Route::redirect('/home', '/')->name('home');

Route::middleware('web')
    ->name('frontend.')
    ->group(function() {
        Route::get('/', 'HomeController@index')->name('home');
        Route::redirect('/index.html', '/');

        Route::get('/luxury.html', 'HomeController@luxury')->name('luxury');
        Route::get('/book.html', 'HomeController@book')->name('book');
        Route::get('/{slug}.html', 'HomeController@detail')->name('detail');
    });

$baseAdminUrl = 'superadmin';

Route::group(['prefix' => $baseAdminUrl], function () {
    Route::middleware('web')
        ->group(function () {
            Auth::routes();
        });

    Route::middleware(['web', 'auth'])
        ->name('backend.')
        ->namespace('Backend')
        ->group(function() {
            //Route::get('remove-image', 'DashboardController@removeImageUpload');
            Route::redirect('/', '/superadmin/dashboard');
            Route::resource('dashboard', 'DashboardController');

            Route::resource('booking', 'BookingController');
            Route::any('booking/ajax/dashboardTable', 'BookingController@ajaxDashboardTable')->name('booking.ajaxDashboardTable');
            Route::any('booking/ajax/dashboardChartist', 'BookingController@ajaxDashboardChartist')->name('booking.ajaxDashboardChartist');

            Route::resource('coupon', 'CouponController');
            Route::resource('cruise-area', 'CruiseAreaController');
            Route::resource('bed-type', 'BedTypeController');

            Route::get('cruise-config', 'CruiseController@editConfig')->name('cruise-config.edit');
            Route::put('cruise-config', 'CruiseController@updateConfig')->name('cruise-config.update');

            Route::resource('cruise', 'CruiseController');
            Route::get('cruise/{id}/album', 'MediaCruiseController@album')->name('media-cruise.album');
            Route::post('cruise/{id}/album/store', 'MediaCruiseController@store')->name('media-cruise.album.store');
            Route::post('cruise/{id}/album/swap-rank', 'MediaCruiseController@swapRank')->name('media-cruise.album.swap-rank');
            Route::delete('media-cruise/{id}/destroy', 'MediaCruiseController@destroy')->name('media-cruise.destroy');

            Route::post('cruise/{id}/is-best-seller', 'CruiseController@isBestSeller')->name('cruise.is-best-seller');

            Route::get('cruise/{id}/cabin/create', 'CabinController@create')->name('cruise.cabin.create');
            Route::get('cruise/{id}/cabin', 'CabinController@index')->name('cruise.cabin.index');
            Route::post('cruise/{id}/cabin/store', 'CabinController@store')->name('cruise.cabin.store');
            Route::get('cabin/{id}', 'CabinController@edit')->name('cabin.edit');
            Route::put('cabin/{id}', 'CabinController@update')->name('cabin.update');
            Route::delete('cabin/{id}/destroy', 'CabinController@destroy')->name('cabin.destroy');

            Route::get('cruise/{id}/policy', 'CruiseController@editPolicy')->name('cruise.policy.edit');
            Route::put('cruise/{id}/policy', 'CruiseController@updatePolicy')->name('cruise.policy.update');
            Route::get('cruise/{id}/additional', 'CruiseController@editAdditional')->name('cruise.additional.edit');
            Route::put('cruise/{id}/additional', 'CruiseController@updateAdditional')->name('cruise.additional.update');

            Route::get('cruise/{id}/journal', 'CruiseJournalController@index')->name('cruise.journal.index');
            Route::get('cruise/{id}/journal/create', 'CruiseJournalController@create')->name('cruise.journal.create');
            Route::post('cruise/{id}/journal/store', 'CruiseJournalController@store')->name('cruise.journal.store');
            Route::get('cruise/{id}/journal_type1', 'CruiseJournalController@editType1')->name('cruise.journal.edit-type-1');
            Route::get('cruise/{id}/journal_type2', 'CruiseJournalController@editType2')->name('cruise.journal.edit-type-2');
            Route::put('cruise/{id}/journal_type1', 'CruiseJournalController@updateType1')->name('cruise.journal.update-type-1');
            Route::put('cruise/{id}/journal_type2', 'CruiseJournalController@updateType2')->name('cruise.journal.update-type-2');
            Route::delete('cruise/{id}/journal_type1', 'CruiseJournalController@destroyType1')->name('cruise.journal.destroy-type-1');
            Route::delete('cruise/{id}/journal_type2', 'CruiseJournalController@destroyType2')->name('cruise.journal.destroy-type-2');

            Route::resource('review', 'ReviewController');
            Route::post('review/{id}/status', 'ReviewController@status')->name('review.status');

            Route::resource('free-service', 'FreeServiceController');
            Route::resource('transfer-service', 'TransferServiceController');
            Route::resource('other-service', 'OtherServiceController');

            Route::resource('faq', 'FaqController');
            Route::put('faq/{id}/status', 'FaqController@status')->name('faq.status');

            Route::get('faq-config', 'FaqController@editConfig')->name('faq-config.edit');
            Route::put('faq-config', 'FaqController@updateConfig')->name('faq-config.update');

            Route::post('uploadPhoto', 'MediaCruiseController@uploadPhoto')->name('uploadPhoto');

            Route::resource('cruise-coupon', 'CruiseCouponController');
            Route::resource('cruise-free-service', 'CruiseFreeServiceController');

            Route::get('cabin/{id}/cabin-price', 'CabinPriceController@index')->name('cabin-price.index');
            //Route::get('cabin/{id}/cabin-price/create', 'CabinPriceController@create')->name('cabin-price.create');
            Route::post('cabin/{id}/cabin-price/store', 'CabinPriceController@store')->name('cabin-price.store');
            Route::get('cabin-price/{id}', 'CabinPriceController@edit')->name('cabin-price.edit');
            Route::put('cabin-price/{id}', 'CabinPriceController@update')->name('cabin-price.update');
            Route::delete('cabin-price/{id}/destroy', 'CabinPriceController@destroy')->name('cabin-price.destroy');

        });
});

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/BedTypeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\BedType;
use DataTables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class BedTypeController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->datatable();
        }

        return view('backend.bed-type.index');
    }

    public function datatable()
    {
        return DataTables::of(BedType::where('id', '>', 0)->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.bed-type.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm btn-edit" data-id="'. $row->id .'" data-name="'. $row->name .'" 
                        data-remote="' . route('backend.bed-type.update', ['id' => $row->id]) . '">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.bed-type.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function create()
    {
        return view('backend.bed-type.create');
    }

    public function store(Request $request)
    {
        $inputs = $request->except('ajax');

        $inputs['name'] = clearXSS($request->name);

        $validator = Validator::make($inputs, [
            'name' => 'required|max:255|unique:bed_types,name,NULL,id,deleted_at,NULL',
        ]);

        if ($request->ajax() && $request->has('ajax')) {
            if ($validator->fails()) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'validator' => $validator->errors()
                ]);
            }

            try {
                BedType::query()->create($inputs);

                return response()->json([
                    'status' => 'success'
                ]);
            } catch (\Exception $e) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'exception' => $e->getMessage()
                ]);
            }
        }

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        try {
            BedType::query()->create($inputs);

            return redirect()->route('backend.bed-type.index')
                ->with('success', __('web.create-successed', ['name' => __('backend.bed-type')]));;
        } catch (\Exception $exception) {
            return back()
                ->with('exception', $exception->getMessage())
                ->withInput()
                ->with('error', __('web.create-errored', ['name' => __('backend.bed-type')]));
        }
    }

    public function show(BedType $BedType)
    {
        //
    }

    public function edit($id)
    {
        $data = BedType::query()->findOrFail($id);

        return view('backend.bed-type.edit', ['data' => $data]);
    }

    public function update(Request $request, $id)
    {
        $inputs = $request->except('ajax');

        $inputs['name'] = clearXSS($request->name);

        $validator = Validator::make($inputs, [
            'name' => 'required|max:255|unique:bed_types,name,'. $id .',id,deleted_at,NULL',
        ]);

        if ($request->ajax() && $request->has('ajax')) {
            if ($validator->fails()) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'validator' => $validator->errors()
                ]);
            }

            try {
                BedType::query()->findOrFail($id)->update($inputs);

                return response()->json([
                    'status' => 'success'
                ]);
            } catch (\Exception $e) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'exception' => $e->getMessage()
                ]);
            }
        }

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        try {
            BedType::query()->findOrFail($id)->update($inputs);

            return redirect()->route('backend.bed-type.index')
                ->with('success', __('web.edit-successed', ['name' => __('backend.bed-type')]));;
        } catch (\Exception $exception) {
            return back()
                ->with('exception', $exception->getMessage())
                ->withInput()
                ->with('error', __('web.edit-errored', ['name' => __('backend.bed-type')]));
        }
    }

    public function destroy($id)
    {
        try {
            BedType::query()->findOrFail($id)->delete();

            return response()->json([
                'status' => 'success'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }
}

app/Http/Controllers/Backend/BookingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\Cabin;
use DataTables;
use Illuminate\Http\Request;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->datatable();
        }

        return view('backend.booking.index');
    }

    public function datatable()
    {
        return DataTables::of(Booking::query()
            ->with('cruise:id,name')
            ->with('cabin:id,name')
            ->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.booking.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.booking.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete-booking text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->addColumn('cruise_name', function ($row) {
                return $row->cruise ? $row->cruise->name : '';
            })
            ->addColumn('cabin_name', function ($row) {
                return $row->cabin ? $row->cabin->name : '';
            })
            ->addColumn('email_phone_number', function ($row) {
                return ($row->email ? $row->email .' - ' : '') . ($row->phone_number ? $row->phone_number : '');
            })
            ->addColumn('passenger', function ($row) {
                return ($row->num_adults ? $row->num_adults .' adults - ' : '') . ($row->num_childs ? $row->num_childs .' childs' : '');
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function ajaxDashboardChartist(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->dataAjaxDashboardChartist($request);
        }

        return null;
    }

    public function dataAjaxDashboardChartist(Request $request)
    {
        try {
            $res = array();

            $fromData = $request->fromDate;
            $toDate = $request->toDate;

            $typeView = $request->typeView;

            switch ($typeView)
            {
                case 'day':
                    $res['labels'] = [];
                    break;
            }

            $res['labels'] = ['0', '1'];
            $res['low'] = 0;
            $res['high'] = 29;
            $res['series'] = ['5', '10'];
            $res['req'] = $request;

            return response()->json([
                'status' => 'success',
                'dataChartist' => $res
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }

    public function ajaxDashboardTable(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->dataAjaxDashboardTable();
        }
    }

    public function dataAjaxDashboardTable()
    {

        return DataTables::of(Booking::query()
            ->with('cruise:id,name')
            ->with('cabin:id,name')
            ->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.booking.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.booking.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete-booking text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->addColumn('cruise_name', function ($row) {
                return $row->cruise ? $row->cruise->name : '';
            })
            ->addColumn('cabin_name', function ($row) {
                return $row->cabin ? $row->cabin->name : '';
            })
            ->addColumn('email_phone_number', function ($row) {
                return ($row->email ? $row->email .' - ' : '') . ($row->phone_number ? $row->phone_number : '');
            })
            ->addColumn('passenger', function ($row) {
                return ($row->num_adults ? $row->num_adults .' adults - ' : '') . ($row->num_childs ? $row->num_childs .' childs' : '');
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        //
    }
}

resources/views/backend/media-cruise/album.blade.php
@extends('layouts.admin')

@section('title', __('backend/cruise.album'))

@push('after-styles')
    {{ Html::style('xtreme-admin/css/sweetalert2.min.css') }}
    {{ Html::style('xtreme-admin/assets/libs/magnific-popup/dist/magnific-popup.css') }}
    <style>
        .inputDnD {
            justify-content: center;
            border-bottom: 2px dashed rgb(54, 190, 166);
        }
        .inputDnD .form-control-file {
            position: relative;
            width: 100%;
            height: 100%;
            min-height: 7em;
            outline: none;
            visibility: hidden;
            cursor: pointer;
            background-color: #c61c23;
            box-shadow: 0 0 5px solid currentColor;
        }
        .inputDnD .form-control-file:before {
            content: attr(data-title);
            position: absolute;
            top: 0.5em;
            left: 0;
            width: 100%;
            min-height: 7em;
            line-height: 2em;
            padding-top: 1.5em;
            opacity: 1;
            visibility: visible;
            text-align: center;
            border: 0.25em dashed currentColor;
            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
            overflow: hidden;
        }
        .inputDnD .form-control-file:hover:before {
            border-style: solid;
            box-shadow: inset 0px 0px 0px 0.25em currentColor;
        }
        .inputDnD img {
            position: absolute;
            height: 70px;
            margin-top: 10px;
        }

        .item .card {
            height: 300px;
            overflow: hidden;
            background: #ddd;
            justify-content: center;
        }
        .item:hover {
            cursor: pointer !important;
        }
    </style>
@endpush

@section('content')
{{ Breadcrumbs::render('cruise-album', $data['id'], $data['name']) }}

<div class="container-fluid">
    <div class="card">
        <div class="card-body">

            @if ($data)

                <div class="row mb-3">
                    <div class="col-12"><h3 class="text-center">{{ __('backend/cruise.album') }} {{ $data['name'] }}</h3></div>
                    <div class="col-12">
                        <div class="row m-b-1">
                            <div class="col-sm-6 offset-sm-3">
                                <form id="form_upload" class="" action="{{ route('backend.media-cruise.album.store', ['id' => $data['id']]) }}" method="post" enctype="multipart/form-data">
                                    @csrf

                                    <div class="form-group inputDnD d-flex">
                                        <label class="sr-only" for="inputFile">File Upload</label>
                                        <img src="/images/drag_image.png" alt="Upload image">
                                        <input type="file" name="image[]" multiple class="form-control-file text-success font-weight-bold" id="inputFile" accept="image/*">
                                        <input type="hidden" name="cruise_id" value="{{ $data['id']}}">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center container-fluid">

                    @if ($medias->count() > 0)
                        <div class="row el-element-overlay" id="list_images" style="width: 100%;">
                            @foreach ($medias as $media)
                                <div class="col-lg-3 col-md-6 item" data-remote-delete="{{ route('backend.media-cruise.destroy', ['id' => $media->id]) }}" data-id="{{ $media->id }}" data-display-ranking="{{ $media->display_ranking }}">
                                    <div class="card">
                                        <div class="el-card-item">
                                            <div class="el-card-avatar el-overlay-1"> <img src="{!! $media->url !!}" alt="Image {{ $loop->index }}">
                                                <div class="el-overlay">
                                                    <ul class="list-style-none el-info">
                                                        <li class="el-item"><a class="btn default btn-outline image-popup-vertical-fit el-link" href="{!! $media->url !!}"><i class="icon-magnifier"></i></a></li>
                                                        <li class="el-item"><a class="btn-remove-image btn default btn-outline el-link" data-media-id="{{ $media->id }}" href="javascript:void(0);"><i class="ti-trash"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @else
                        <p>{{ __('backend/cruise.album-not-found') }}</p>
                    @endif
                </div>

            @else
                <p>{{ __('web.not-found', ['name' => __('backend/cruise.album')]) }}</p>
            @endif
        </div>
    </div>
</div>
@endsection

@push('after-scripts')
    {!! Html::script('xtreme-admin/js/sweetalert2.all.min.js') !!}
    {!! Html::script('xtreme-admin/assets/libs/magnific-popup/dist/jquery.magnific-popup.min.js') !!}
    {!! Html::script('xtreme-admin/assets/libs/magnific-popup/meg.init.js') !!}
    {!! Html::script('js/Sortable.js') !!}

    <script>
        $(document).ready(function () {

            @if ($medias->count() > 0)

            new Sortable(document.getElementById('list_images'), {
                swap: true,
                swapClass: 'highlight',
                animation: 150,
                onEnd: function (evt) {
                    var itemEl = evt.item;
                    var pre = evt.oldIndex + 1;
                    var after = evt.newIndex + 1;
                    pre = $('#list_images > div:nth-child('+ pre +')');
                    after = $('#list_images > div:nth-child('+ after +')');
                    preIdMedia = pre.data('id');
                    preDisplayRankingMedia = pre.data('display-ranking');
                    afterIdMedia = after.data('id');
                    afterDisplayRankingMedia = after.data('display-ranking');

                    $.ajax({
                        url: '{{ route('backend.media-cruise.album.swap-rank', ['id' => $data['id']]) }}',
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            '_token': '{{ csrf_token() }}',
                            'preId': preIdMedia,
                            'afterId': afterIdMedia,
                            'preDisplayRanking': preDisplayRankingMedia,
                            'afterDisplayRanking': afterDisplayRankingMedia
                        },
                        success: function (data) {
                            if (data.status === 'success') {
                                toastr.success(convertMsg("Edit {{ __('backend/cruise.display_ranking') }} successful!"));
                            } else {
                                toastr.error(convertMsg("Edit {{ __('backend/cruise.display_ranking') }} successful!"));
                            }
                        },
                    });
                }
            });

            @endif

            function checkImage(filename) {
                var fileType = filename.split('.').pop().trim().toLowerCase();
                var validImageTypes = ["gif", "jpeg", "png", "jpg"];
                if ($.inArray(fileType, validImageTypes) < 0) {
                    alert('{{ __('web.invalid-image-type') }}');
                    return false;
                }
                return true;
            }

            $('#inputFile').change(function(e) {
                var files = $('#inputFile')[0].files;
                var upload_count = files.length;
                if (upload_count > 5) {
                    alert('{{ __('web.max-upload-album', ['max' => 5]) }}');
                    $(this).val('');
                    return false;
                }

                for (var i=0, f; f=files[i]; i++) {
                    var filename = f.name;
                    if (!checkImage(filename)) {
                        $(this).val('');
                        return false;
                    }
                }

                $('#form_upload').submit();
            });

            $('.btn-remove-image').click(function(e) {
                e.preventDefault();

                swal.fire({
                    title: '{{ __('web.confirm-delete') }}',
                    text: '{{ __('web.confirm-delete-detail') }}',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: '{{ __('web.accept') }}',
                    cancelButtonText: '{{ __('web.cancel') }}'
                }).then((result) => {
                    if (result.value) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            }
                        });

                        var item = $(this).parents('.item');

                        if (item.data('id') > 0) {
                            $.ajax({
                                url: item.data('remote-delete'),
                                type: 'DELETE',
                                dataType: 'json',
                                data: {id: item.data('id')},
                                success: function (data) {
                                    if (data.status === 'success') {
                                        toastr.success(convertMsg("Delete image successful!"));
                                        item.remove();
                                    } else {
                                        toastr.error(convertMsg("Delete image failed!"));
                                    }
                                },
                            });
                        }
                    }
                });
            });
        });
    </script>
@endpush