routes/web.php
<?php

Route::redirect('/home', '/')->name('home');

Route::middleware('web')
    ->name('frontend.')
    ->group(function() {
        Route::get('/', 'HomeController@index')->name('home');
        Route::redirect('/index.html', '/');

        Route::get('/luxury.html', 'HomeController@luxury')->name('luxury');
        Route::get('/book.html', 'HomeController@book')->name('book');
        Route::get('/{slug}.html', 'HomeController@detail')->name('detail');
    });

$baseAdminUrl = 'superadmin';

Route::group(['prefix' => $baseAdminUrl], function () {
    Route::middleware('web')
        ->group(function () {
            Auth::routes();
        });

    Route::middleware(['web', 'auth'])
        ->name('backend.')
        ->namespace('Backend')
        ->group(function() {
            //Route::get('remove-image', 'DashboardController@removeImageUpload');
            Route::redirect('/', '/superadmin/dashboard');
            Route::resource('dashboard', 'DashboardController');

            Route::resource('booking', 'BookingController');
            Route::any('booking/ajax/dashboardTable', 'BookingController@ajaxDashboardTable')->name('booking.ajaxDashboardTable');
            Route::any('booking/ajax/dashboardChartist', 'BookingController@ajaxDashboardChartist')->name('booking.ajaxDashboardChartist');

            Route::resource('coupon', 'CouponController');
            Route::resource('cruise-area', 'CruiseAreaController');
            Route::resource('bed-type', 'BedTypeController');

            Route::get('cruise-config', 'CruiseController@editConfig')->name('cruise-config.edit');
            Route::put('cruise-config', 'CruiseController@updateConfig')->name('cruise-config.update');

            Route::resource('cruise', 'CruiseController');
            Route::get('cruise/{id}/album', 'MediaCruiseController@album')->name('media-cruise.album');
            Route::post('cruise/{id}/album/store', 'MediaCruiseController@store')->name('media-cruise.album.store');
            Route::post('cruise/{id}/album/swap-rank', 'MediaCruiseController@swapRank')->name('media-cruise.album.swap-rank');
            Route::delete('media-cruise/{id}/destroy', 'MediaCruiseController@destroy')->name('media-cruise.destroy');

            Route::post('cruise/{id}/is-best-seller', 'CruiseController@isBestSeller')->name('cruise.is-best-seller');

            Route::get('cruise/{id}/cabin/create', 'CabinController@create')->name('cruise.cabin.create');
            Route::get('cruise/{id}/cabin', 'CabinController@index')->name('cruise.cabin.index');
            Route::post('cruise/{id}/cabin/store', 'CabinController@store')->name('cruise.cabin.store');
            Route::get('cabin/{id}', 'CabinController@edit')->name('cabin.edit');
            Route::put('cabin/{id}', 'CabinController@update')->name('cabin.update');
            Route::delete('cabin/{id}/destroy', 'CabinController@destroy')->name('cabin.destroy');

            Route::get('cruise/{id}/policy', 'CruiseController@editPolicy')->name('cruise.policy.edit');
            Route::put('cruise/{id}/policy', 'CruiseController@updatePolicy')->name('cruise.policy.update');
            Route::get('cruise/{id}/additional', 'CruiseController@editAdditional')->name('cruise.additional.edit');
            Route::put('cruise/{id}/additional', 'CruiseController@updateAdditional')->name('cruise.additional.update');

            Route::get('cruise/{id}/journal', 'CruiseJournalController@index')->name('cruise.journal.index');
            Route::get('cruise/{id}/journal/create', 'CruiseJournalController@create')->name('cruise.journal.create');
            Route::post('cruise/{id}/journal/store', 'CruiseJournalController@store')->name('cruise.journal.store');
            Route::get('cruise/{id}/journal_type1', 'CruiseJournalController@editType1')->name('cruise.journal.edit-type-1');
            Route::get('cruise/{id}/journal_type2', 'CruiseJournalController@editType2')->name('cruise.journal.edit-type-2');
            Route::put('cruise/{id}/journal_type1', 'CruiseJournalController@updateType1')->name('cruise.journal.update-type-1');
            Route::put('cruise/{id}/journal_type2', 'CruiseJournalController@updateType2')->name('cruise.journal.update-type-2');
            Route::delete('cruise/{id}/journal_type1', 'CruiseJournalController@destroyType1')->name('cruise.journal.destroy-type-1');
            Route::delete('cruise/{id}/journal_type2', 'CruiseJournalController@destroyType2')->name('cruise.journal.destroy-type-2');

            Route::resource('review', 'ReviewController');
            Route::post('review/{id}/status', 'ReviewController@status')->name('review.status');

            Route::resource('free-service', 'FreeServiceController');
            Route::resource('transfer-service', 'TransferServiceController');
            Route::resource('other-service', 'OtherServiceController');

            Route::resource('faq', 'FaqController');
            Route::put('faq/{id}/status', 'FaqController@status')->name('faq.status');

            Route::get('faq-config', 'FaqController@editConfig')->name('faq-config.edit');
            Route::put('faq-config', 'FaqController@updateConfig')->name('faq-config.update');

            Route::post('uploadPhoto', 'MediaCruiseController@uploadPhoto')->name('uploadPhoto');

            Route::resource('cruise-coupon', 'CruiseCouponController');
            Route::resource('cruise-free-service', 'CruiseFreeServiceController');

            Route::get('cabin/{id}/cabin-price', 'CabinPriceController@index')->name('cabin-price.index');
            //Route::get('cabin/{id}/cabin-price/create', 'CabinPriceController@create')->name('cabin-price.create');
            Route::post('cabin/{id}/cabin-price/store', 'CabinPriceController@store')->name('cabin-price.store');
            Route::get('cabin-price/{id}', 'CabinPriceController@edit')->name('cabin-price.edit');
            Route::put('cabin-price/{id}', 'CabinPriceController@update')->name('cabin-price.update');
            Route::delete('cabin-price/{id}/destroy', 'CabinPriceController@destroy')->name('cabin-price.destroy');

        });
});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Faq extends Model
{
    use SoftDeletes;
    protected $guarded = array();
}

app/Http/Controllers/Backend/BedTypeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\BedType;
use DataTables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class BedTypeController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->datatable();
        }

        return view('backend.bed-type.index');
    }

    public function datatable()
    {
        return DataTables::of(BedType::where('id', '>', 0)->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.bed-type.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm btn-edit" data-id="'. $row->id .'" data-name="'. $row->name .'" 
                        data-remote="' . route('backend.bed-type.update', ['id' => $row->id]) . '">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.bed-type.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function create()
    {
        return view('backend.bed-type.create');
    }

    public function store(Request $request)
    {
        $inputs = $request->except('ajax');

        $inputs['name'] = clearXSS($request->name);

        $validator = Validator::make($inputs, [
            'name' => 'required|max:255|unique:bed_types,name,NULL,id,deleted_at,NULL',
        ]);

        if ($request->ajax() && $request->has('ajax')) {
            if ($validator->fails()) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'validator' => $validator->errors()
                ]);
            }

            try {
                BedType::query()->create($inputs);

                return response()->json([
                    'status' => 'success'
                ]);
            } catch (\Exception $e) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'exception' => $e->getMessage()
                ]);
            }
        }

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        try {
            BedType::query()->create($inputs);

            return redirect()->route('backend.bed-type.index')
                ->with('success', __('web.create-successed', ['name' => __('backend.bed-type')]));;
        } catch (\Exception $exception) {
            return back()
                ->with('exception', $exception->getMessage())
                ->withInput()
                ->with('error', __('web.create-errored', ['name' => __('backend.bed-type')]));
        }
    }

    public function show(BedType $BedType)
    {
        //
    }

    public function edit($id)
    {
        $data = BedType::query()->findOrFail($id);

        return view('backend.bed-type.edit', ['data' => $data]);
    }

    public function update(Request $request, $id)
    {
        $inputs = $request->except('ajax');

        $inputs['name'] = clearXSS($request->name);

        $validator = Validator::make($inputs, [
            'name' => 'required|max:255|unique:bed_types,name,'. $id .',id,deleted_at,NULL',
        ]);

        if ($request->ajax() && $request->has('ajax')) {
            if ($validator->fails()) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'validator' => $validator->errors()
                ]);
            }

            try {
                BedType::query()->findOrFail($id)->update($inputs);

                return response()->json([
                    'status' => 'success'
                ]);
            } catch (\Exception $e) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'exception' => $e->getMessage()
                ]);
            }
        }

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        try {
            BedType::query()->findOrFail($id)->update($inputs);

            return redirect()->route('backend.bed-type.index')
                ->with('success', __('web.edit-successed', ['name' => __('backend.bed-type')]));;
        } catch (\Exception $exception) {
            return back()
                ->with('exception', $exception->getMessage())
                ->withInput()
                ->with('error', __('web.edit-errored', ['name' => __('backend.bed-type')]));
        }
    }

    public function destroy($id)
    {
        try {
            BedType::query()->findOrFail($id)->delete();

            return response()->json([
                'status' => 'success'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }
}

app/Http/Controllers/Backend/BookingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\Cabin;
use DataTables;
use Illuminate\Http\Request;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->datatable();
        }

        return view('backend.booking.index');
    }

    public function datatable()
    {
        return DataTables::of(Booking::query()
            ->with('cruise:id,name')
            ->with('cabin:id,name')
            ->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.booking.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.booking.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete-booking text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->addColumn('cruise_name', function ($row) {
                return $row->cruise ? $row->cruise->name : '';
            })
            ->addColumn('cabin_name', function ($row) {
                return $row->cabin ? $row->cabin->name : '';
            })
            ->addColumn('email_phone_number', function ($row) {
                return ($row->email ? $row->email .' - ' : '') . ($row->phone_number ? $row->phone_number : '');
            })
            ->addColumn('passenger', function ($row) {
                return ($row->num_adults ? $row->num_adults .' adults - ' : '') . ($row->num_childs ? $row->num_childs .' childs' : '');
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function ajaxDashboardChartist(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->dataAjaxDashboardChartist($request);
        }

        return null;
    }

    public function dataAjaxDashboardChartist(Request $request)
    {
        try {
            $res = array();

            $fromData = $request->fromDate;
            $toDate = $request->toDate;

            $typeView = $request->typeView;

            switch ($typeView)
            {
                case 'day':
                    $res['labels'] = [];
                    break;
            }

            $res['labels'] = ['0', '1'];
            $res['low'] = 0;
            $res['high'] = 29;
            $res['series'] = ['5', '10'];
            $res['req'] = $request;

            return response()->json([
                'status' => 'success',
                'dataChartist' => $res
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }

    public function ajaxDashboardTable(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->dataAjaxDashboardTable();
        }
    }

    public function dataAjaxDashboardTable()
    {

        return DataTables::of(Booking::query()
            ->with('cruise:id,name')
            ->with('cabin:id,name')
            ->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.booking.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.booking.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete-booking text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->addColumn('cruise_name', function ($row) {
                return $row->cruise ? $row->cruise->name : '';
            })
            ->addColumn('cabin_name', function ($row) {
                return $row->cabin ? $row->cabin->name : '';
            })
            ->addColumn('email_phone_number', function ($row) {
                return ($row->email ? $row->email .' - ' : '') . ($row->phone_number ? $row->phone_number : '');
            })
            ->addColumn('passenger', function ($row) {
                return ($row->num_adults ? $row->num_adults .' adults - ' : '') . ($row->num_childs ? $row->num_childs .' childs' : '');
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        //
    }
}

resources/views/backend/faq/create.blade.php
@extends('layouts.admin')

@section('title', __('web.creating', ['name' => __('backend.faq')]))

@section('content')
{{ Breadcrumbs::render('faq-create') }}

<div class="container-fluid">
    <div class="card">
        <div class="card-body mx-5">
            <form class="mt-3" action="{{ route('backend.faq.store') }}" method="post" enctype="multipart/form-data">
                @csrf

                <h3 class="card-title text-center">{{ __('web.creating', ['name' => __('backend.faq')]) }}</h3>
                <div class="form-body">
                    <div class="card-body pt-0">
                        <div class="row pt-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="question">{{ __('backend/faq.question') }} <span class="text-danger">(*)</span></label>
                                    <input id="question" type="text" data-name-show="{{ __('backend/faq.question') }}"  class="custom-validate form-control form-control-lg @error('question') is-invalid @enderror"
                                           name="question" value="{{ old('question') }}" maxlength="100"
                                           required>

                                    @error('question')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="subject">{{ __('backend/faq.subject') }} <span class="text-danger">(*)</span></label>
                                    <select name="subject" data-name-show="{{ __('backend/faq.subject') }}" id="subject" data-name-show="{{ __('backend/faq.subject') }}"  class="select2 custom-validate form-control form-control-lg @error('subject') is-invalid @enderror" required>
                                        <option value="" disabled selected>{{ __('web.select-an-option') }}</option>
                                        <option value="Billing and Payments"{{ old('subject') == 'Billing and Payments' ? ' selected' : '' }}>Billing and Payments</option>
                                        <option value="Booking and Reservation"{{ old('subject') == 'Booking and Reservation' ? ' selected' : '' }}>Booking and Reservation</option>
                                        <option value="Cancellation and Refund"{{ old('subject') == 'Cancellation and Refund' ? ' selected' : '' }}>Cancellation and Refund</option>
                                        <option value="Getting on board"{{ old('subject') == 'Getting on board' ? ' selected' : '' }}>Getting on board</option>
                                        <option value="Plan your trip"{{ old('subject') == 'Plan your trip' ? ' selected' : '' }}>Plan your trip</option>
                                        <option value="Transportation"{{ old('subject') == 'Transportation' ? ' selected' : '' }}>Transportation</option>
                                    </select>

                                    @error('subject')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="row pt-3">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label" for="answer">{{ __('backend/faq.answer') }} <span class="text-danger">(*)</span></label>
                                    <textarea id="answer" name="answer" required
                                              class="form-control form-control-lg">{{ old('answer') }}&nbsp;</textarea>

                                    @error('answer')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                    <span class="invalid-feedback d-none" id="validate_answer" role="alert">
                                        <strong></strong>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="card-body text-center">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> {{ __('web.save') }}</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('after-scripts')
    {!! Html::script('xtreme-admin/assets/libs/ckeditor/ckeditor.js') !!}

    <script>
        $(document).ready(function () {
            CKEDITOR.config.filebrowserImageUploadUrl = '{!! route('backend.uploadPhoto').'?_token='.csrf_token() !!}';
            CKEDITOR.config.height = '300px';
            CKEDITOR.replace(document.querySelector( '#answer' ));

            $.each($('.select2'), function (i, e) {
                $(e).select2({
                    placeholder: '{{ __('web.select-an-option') }}'
                });
            });

            listenValidateForm();
            $('button[type=submit]').click(function (e) {
                if (CKEDITOR.instances.answer.getData() == '') {
                    var msg = 'The {{ __('backend/faq.answer') }} field is required.';
                    addErrorValidateForm($('#validate_answer'), msg);
                }

                validateForm(e);
            });
        });
    </script>
@endpush

resources/views/backend/faq/index.blade.php
@extends('layouts.admin')

@section('title', __('backend.faq'))

@push('after-styles')
    {{ Html::style('xtreme-admin/css/datatables.min.css') }}
    {{ Html::style('xtreme-admin/assets/libs/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css') }}
@endpush

@section('content')
{{ Breadcrumbs::render('faq') }}

<div class="container-fluid">
    <div class="card">
        <div class="card-body">

            <div class="row">
                <div class="col-6"><h3>{{ __('backend.faq') }}</h3></div>
                <div class="col-6 text-right">
                    <a href="{{ route('backend.faq-config.edit') }}" class="btn btn-success">{{ __('backend.faq-config') }}</a>
                    <a href="{{ route('backend.faq.create') }}" class="btn btn-primary">{{ __('web.create') }}</a>
                </div>
            </div>

            <div class="table-responsive mt-3">
                <table id="the_table" class="table table-striped table-bordered display" style="width:100%">
                    <thead>
                    <tr>
                        <th>{{ __('No.') }}</th>
                        <th>{{ __('backend/faq.question') }}</th>
                        <th>{{ __('backend/faq.subject') }}</th>
                        <th>{{ __('backend/faq.status') }}</th>
                        <th>{{ __('web.action') }}</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('after-scripts')
    {!! Html::script('xtreme-admin/js/datatables.min.js') !!}
    {!! Html::script('xtreme-admin/assets/libs/bootstrap-switch/dist/js/bootstrap-switch.min.js') !!}

    <script>
        $(function () {
            "use strict";

            var table = $('#the_table').DataTable({
                dom: '<"pull-left"f><"pull-right"l>tip',
                processing: false,
                language: {
                    url: "{{ url('xtreme-admin/js/datatablelanguage.json') }}"
                },
                serverSide: true,
                ajax: "{{ route('backend.faq.index') }}?ajax",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', width: '30px', className: 'text-center', searchable: false},
                    {data: 'question', name: 'question', orderable: false},
                    {data: 'subject', name: 'subject', width: '200px'},
                    {data: 'col_status', name: 'col_status', className: 'px-0 text-center', width: '170px', searchable: false},
                    {data: 'action', name: 'action', orderable: false, className: 'text-center', searchable: false, width: '150px'},
                ],
                drawCallback: function (setting, json) {
                    setupBtSwitchDatatable();
                }
            }).on('error.dt', function (e, settings, techNote, message) {
                console.log(e);
            });

            setupBtDeleteDatatable(table, '{{ __('backend.faq') }}');
        });
    </script>
@endpush