routes/web.php
<?php

Route::redirect('/home', '/')->name('home');

Route::middleware('web')
    ->name('frontend.')
    ->group(function() {
        Route::get('/', 'HomeController@index')->name('home');
        Route::redirect('/index.html', '/');

        Route::get('/luxury.html', 'HomeController@luxury')->name('luxury');
        Route::get('/book.html', 'HomeController@book')->name('book');
        Route::get('/{slug}.html', 'HomeController@detail')->name('detail');
    });

$baseAdminUrl = 'superadmin';

Route::group(['prefix' => $baseAdminUrl], function () {
    Route::middleware('web')
        ->group(function () {
            Auth::routes();
        });

    Route::middleware(['web', 'auth'])
        ->name('backend.')
        ->namespace('Backend')
        ->group(function() {
            //Route::get('remove-image', 'DashboardController@removeImageUpload');
            Route::redirect('/', '/superadmin/dashboard');
            Route::resource('dashboard', 'DashboardController');

            Route::resource('booking', 'BookingController');
            Route::any('booking/ajax/dashboardTable', 'BookingController@ajaxDashboardTable')->name('booking.ajaxDashboardTable');
            Route::any('booking/ajax/dashboardChartist', 'BookingController@ajaxDashboardChartist')->name('booking.ajaxDashboardChartist');

            Route::resource('coupon', 'CouponController');
            Route::resource('cruise-area', 'CruiseAreaController');
            Route::resource('bed-type', 'BedTypeController');

            Route::get('cruise-config', 'CruiseController@editConfig')->name('cruise-config.edit');
            Route::put('cruise-config', 'CruiseController@updateConfig')->name('cruise-config.update');

            Route::resource('cruise', 'CruiseController');
            Route::get('cruise/{id}/album', 'MediaCruiseController@album')->name('media-cruise.album');
            Route::post('cruise/{id}/album/store', 'MediaCruiseController@store')->name('media-cruise.album.store');
            Route::post('cruise/{id}/album/swap-rank', 'MediaCruiseController@swapRank')->name('media-cruise.album.swap-rank');
            Route::delete('media-cruise/{id}/destroy', 'MediaCruiseController@destroy')->name('media-cruise.destroy');

            Route::post('cruise/{id}/is-best-seller', 'CruiseController@isBestSeller')->name('cruise.is-best-seller');

            Route::get('cruise/{id}/cabin/create', 'CabinController@create')->name('cruise.cabin.create');
            Route::get('cruise/{id}/cabin', 'CabinController@index')->name('cruise.cabin.index');
            Route::post('cruise/{id}/cabin/store', 'CabinController@store')->name('cruise.cabin.store');
            Route::get('cabin/{id}', 'CabinController@edit')->name('cabin.edit');
            Route::put('cabin/{id}', 'CabinController@update')->name('cabin.update');
            Route::delete('cabin/{id}/destroy', 'CabinController@destroy')->name('cabin.destroy');

            Route::get('cruise/{id}/policy', 'CruiseController@editPolicy')->name('cruise.policy.edit');
            Route::put('cruise/{id}/policy', 'CruiseController@updatePolicy')->name('cruise.policy.update');
            Route::get('cruise/{id}/additional', 'CruiseController@editAdditional')->name('cruise.additional.edit');
            Route::put('cruise/{id}/additional', 'CruiseController@updateAdditional')->name('cruise.additional.update');

            Route::get('cruise/{id}/journal', 'CruiseJournalController@index')->name('cruise.journal.index');
            Route::get('cruise/{id}/journal/create', 'CruiseJournalController@create')->name('cruise.journal.create');
            Route::post('cruise/{id}/journal/store', 'CruiseJournalController@store')->name('cruise.journal.store');
            Route::get('cruise/{id}/journal_type1', 'CruiseJournalController@editType1')->name('cruise.journal.edit-type-1');
            Route::get('cruise/{id}/journal_type2', 'CruiseJournalController@editType2')->name('cruise.journal.edit-type-2');
            Route::put('cruise/{id}/journal_type1', 'CruiseJournalController@updateType1')->name('cruise.journal.update-type-1');
            Route::put('cruise/{id}/journal_type2', 'CruiseJournalController@updateType2')->name('cruise.journal.update-type-2');
            Route::delete('cruise/{id}/journal_type1', 'CruiseJournalController@destroyType1')->name('cruise.journal.destroy-type-1');
            Route::delete('cruise/{id}/journal_type2', 'CruiseJournalController@destroyType2')->name('cruise.journal.destroy-type-2');

            Route::resource('review', 'ReviewController');
            Route::post('review/{id}/status', 'ReviewController@status')->name('review.status');

            Route::resource('free-service', 'FreeServiceController');
            Route::resource('transfer-service', 'TransferServiceController');
            Route::resource('other-service', 'OtherServiceController');

            Route::resource('faq', 'FaqController');
            Route::put('faq/{id}/status', 'FaqController@status')->name('faq.status');

            Route::get('faq-config', 'FaqController@editConfig')->name('faq-config.edit');
            Route::put('faq-config', 'FaqController@updateConfig')->name('faq-config.update');

            Route::post('uploadPhoto', 'MediaCruiseController@uploadPhoto')->name('uploadPhoto');

            Route::resource('cruise-coupon', 'CruiseCouponController');
            Route::resource('cruise-free-service', 'CruiseFreeServiceController');

            Route::get('cabin/{id}/cabin-price', 'CabinPriceController@index')->name('cabin-price.index');
            //Route::get('cabin/{id}/cabin-price/create', 'CabinPriceController@create')->name('cabin-price.create');
            Route::post('cabin/{id}/cabin-price/store', 'CabinPriceController@store')->name('cabin-price.store');
            Route::get('cabin-price/{id}', 'CabinPriceController@edit')->name('cabin-price.edit');
            Route::put('cabin-price/{id}', 'CabinPriceController@update')->name('cabin-price.update');
            Route::delete('cabin-price/{id}/destroy', 'CabinPriceController@destroy')->name('cabin-price.destroy');

        });
});

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/BedTypeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\BedType;
use DataTables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class BedTypeController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->datatable();
        }

        return view('backend.bed-type.index');
    }

    public function datatable()
    {
        return DataTables::of(BedType::where('id', '>', 0)->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.bed-type.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm btn-edit" data-id="'. $row->id .'" data-name="'. $row->name .'" 
                        data-remote="' . route('backend.bed-type.update', ['id' => $row->id]) . '">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.bed-type.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function create()
    {
        return view('backend.bed-type.create');
    }

    public function store(Request $request)
    {
        $inputs = $request->except('ajax');

        $inputs['name'] = clearXSS($request->name);

        $validator = Validator::make($inputs, [
            'name' => 'required|max:255|unique:bed_types,name,NULL,id,deleted_at,NULL',
        ]);

        if ($request->ajax() && $request->has('ajax')) {
            if ($validator->fails()) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'validator' => $validator->errors()
                ]);
            }

            try {
                BedType::query()->create($inputs);

                return response()->json([
                    'status' => 'success'
                ]);
            } catch (\Exception $e) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'exception' => $e->getMessage()
                ]);
            }
        }

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        try {
            BedType::query()->create($inputs);

            return redirect()->route('backend.bed-type.index')
                ->with('success', __('web.create-successed', ['name' => __('backend.bed-type')]));;
        } catch (\Exception $exception) {
            return back()
                ->with('exception', $exception->getMessage())
                ->withInput()
                ->with('error', __('web.create-errored', ['name' => __('backend.bed-type')]));
        }
    }

    public function show(BedType $BedType)
    {
        //
    }

    public function edit($id)
    {
        $data = BedType::query()->findOrFail($id);

        return view('backend.bed-type.edit', ['data' => $data]);
    }

    public function update(Request $request, $id)
    {
        $inputs = $request->except('ajax');

        $inputs['name'] = clearXSS($request->name);

        $validator = Validator::make($inputs, [
            'name' => 'required|max:255|unique:bed_types,name,'. $id .',id,deleted_at,NULL',
        ]);

        if ($request->ajax() && $request->has('ajax')) {
            if ($validator->fails()) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'validator' => $validator->errors()
                ]);
            }

            try {
                BedType::query()->findOrFail($id)->update($inputs);

                return response()->json([
                    'status' => 'success'
                ]);
            } catch (\Exception $e) {
                return response()->json([
                    'status' => 'error',
                    'data' => $inputs,
                    'exception' => $e->getMessage()
                ]);
            }
        }

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        try {
            BedType::query()->findOrFail($id)->update($inputs);

            return redirect()->route('backend.bed-type.index')
                ->with('success', __('web.edit-successed', ['name' => __('backend.bed-type')]));;
        } catch (\Exception $exception) {
            return back()
                ->with('exception', $exception->getMessage())
                ->withInput()
                ->with('error', __('web.edit-errored', ['name' => __('backend.bed-type')]));
        }
    }

    public function destroy($id)
    {
        try {
            BedType::query()->findOrFail($id)->delete();

            return response()->json([
                'status' => 'success'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }
}

app/Http/Controllers/Backend/BookingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\Cabin;
use DataTables;
use Illuminate\Http\Request;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->datatable();
        }

        return view('backend.booking.index');
    }

    public function datatable()
    {
        return DataTables::of(Booking::query()
            ->with('cruise:id,name')
            ->with('cabin:id,name')
            ->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.booking.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.booking.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete-booking text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->addColumn('cruise_name', function ($row) {
                return $row->cruise ? $row->cruise->name : '';
            })
            ->addColumn('cabin_name', function ($row) {
                return $row->cabin ? $row->cabin->name : '';
            })
            ->addColumn('email_phone_number', function ($row) {
                return ($row->email ? $row->email .' - ' : '') . ($row->phone_number ? $row->phone_number : '');
            })
            ->addColumn('passenger', function ($row) {
                return ($row->num_adults ? $row->num_adults .' adults - ' : '') . ($row->num_childs ? $row->num_childs .' childs' : '');
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function ajaxDashboardChartist(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->dataAjaxDashboardChartist($request);
        }

        return null;
    }

    public function dataAjaxDashboardChartist(Request $request)
    {
        try {
            $res = array();

            $fromData = $request->fromDate;
            $toDate = $request->toDate;

            $typeView = $request->typeView;

            switch ($typeView)
            {
                case 'day':
                    $res['labels'] = [];
                    break;
            }

            $res['labels'] = ['0', '1'];
            $res['low'] = 0;
            $res['high'] = 29;
            $res['series'] = ['5', '10'];
            $res['req'] = $request;

            return response()->json([
                'status' => 'success',
                'dataChartist' => $res
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error'
            ]);
        }
    }

    public function ajaxDashboardTable(Request $request)
    {
        if ($request->ajax() && $request->has('ajax')) {
            return $this->dataAjaxDashboardTable();
        }
    }

    public function dataAjaxDashboardTable()
    {

        return DataTables::of(Booking::query()
            ->with('cruise:id,name')
            ->with('cabin:id,name')
            ->get())
            ->addIndexColumn()
            ->addColumn('action', function ($row) {

                $btn = '<a href="' . route('backend.booking.edit', ['id' => $row->id]) . '" 
                        class="btn btn-primary btn-sm">'.__('web.edit').'</a>';

                $btn .= '<a href="#" data-remote="' . route('backend.booking.destroy', ['id' => $row->id]) . '" 
                        class="btn btn-dark btn-sm btn-delete-booking text-white">'.__('web.delete').'</a>';

                return $btn;
            })
            ->addColumn('cruise_name', function ($row) {
                return $row->cruise ? $row->cruise->name : '';
            })
            ->addColumn('cabin_name', function ($row) {
                return $row->cabin ? $row->cabin->name : '';
            })
            ->addColumn('email_phone_number', function ($row) {
                return ($row->email ? $row->email .' - ' : '') . ($row->phone_number ? $row->phone_number : '');
            })
            ->addColumn('passenger', function ($row) {
                return ($row->num_adults ? $row->num_adults .' adults - ' : '') . ($row->num_childs ? $row->num_childs .' childs' : '');
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        //
    }
}

resources/views/backend/cruise-free-service/create.blade.php
@extends('layouts.admin')

@section('title', __('web.creating', ['name' => __('backend.cruise-free-service')]))

@push('after-styles')
    {{ Html::style('xtreme-admin/pickadate/lib/themes/classic.css') }}
    {{ Html::style('xtreme-admin/pickadate/lib/themes/classic.date.css') }}
    {{ Html::style('xtreme-admin/pickadate/lib/themes/classic.time.css') }}
@endpush

@section('content')
    {{ Breadcrumbs::render('cruise-free-service-create') }}

<div class="container-fluid">
    <div class="card">
        <div class="card-body container">
            <h3 class="card-title text-center">{{ __('web.creating', ['name' => __('backend.cruise-free-service')]) }}</h3>
            <form class="mt-3" action="{{ route('backend.cruise-free-service.store') }}" method="post">
                @csrf

                <div class="row pt-3">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label" for="name">{{ __('backend/cruise-free-service.cruise') }} <span class="text-danger">(*)</span></label>
                            <select name="cruise_id[]" multiple="multiple" id="cruise_id" class="select2 form-control form-control-lg @error('cruise_id') is-invalid @enderror" required>
                                <option value="" disabled>{{ __('web.select-an-option') }}</option>
                                <option value="-1">{{ __('backend/cruise-free-service.all-cruise') }}</option>
                                @foreach ($listCruises as $cruise)
                                    <option value="{{ $cruise->id }}"{{ old('cruise_id') == $cruise->id ? ' selected' : '' }}>{{ $cruise->name }}</option>
                                @endforeach
                            </select>

                            @error('cruise_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <span class="invalid-feedback d-none" id="validate_cruise_id" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="row pt-3">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="free_service_id">{{ __('backend/cruise-free-service.free-service') }} <span class="text-danger">(*)</span></label>
                            <div class="w-100"></div>
                            @foreach ($listFreeServices as $freeService)
                                <div class="form-check pl-0 mt-2">
                                    <div class="custom-control custom-checkbox">
                                        <input id="checkbox_free_service_{{ $freeService->id }}" type="checkbox"
                                               class="custom-control-input form-check-input" name="free_service[]"
                                               value="{{ $freeService->id }}"{{ old('free_service') ? (in_array($freeService->id, old('free_service')) ? ' checked' : '') : '' }}>
                                        <label for="checkbox_free_service_{{ $freeService->id }}"
                                               class="custom-control-label">{{ $freeService->name }}</label>
                                    </div>
                                </div>
                                <div class="w-100"></div>
                            @endforeach

                            @error('free_service_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <span class="invalid-feedback d-none" id="validate_free_service_id" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="row pt-3">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label" for="from">{{ __('backend/cruise-free-service.from') }} <span class="text-danger">(*)</span></label>

                            <div class="input-group col pl-0">
                                <input id="from" value="{{ old('from') }}" name="from" class="form-control form-control-lg datepicker @error('from') is-invalid @enderror" type="text" placeholder="Default Date" >
                            </div>

                            @error('from')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <span class="invalid-feedback d-none" id="validate_from" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label" for="to">{{ __('backend/cruise-free-service.to') }} <span class="text-danger">(*)</span></label>

                            <div class="input-group col pl-0">
                                <input id="to" value="{{ old('to') }}" name="to" class="form-control form-control-lg datepicker @error('to') is-invalid @enderror" type="text" placeholder="Default Date" >
                            </div>

                            @error('to')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <span class="invalid-feedback d-none" id="validate_to" role="alert">
                                <strong></strong>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="text-center mt-3">
                    <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('after-scripts')
    {!! Html::script('xtreme-admin/pickadate/lib/picker.js') !!}
    {!! Html::script('xtreme-admin/pickadate/lib/picker.date.js') !!}
    {!! Html::script('xtreme-admin/pickadate/lib/picker.time.js') !!}

    <script>
        $(document).ready(function () {
            $.each($('.select2'), function (i, e) {
                $(e).select2({
                    placeholder: '{{ __('web.select-an-option') }}'
                });
            });

            $('#cruise_id').on('select2:select', function(e) {
                var arr = $(this).val();
                if (arr.includes("-1")) {
                    $(this).val(-1);
                    $(this).trigger('change');
                }
            });

            listenValidateForm();

            $('button[type=submit]').click(function (e) {
                var checked = $("input[name=coupon_id]:checked").length;
                if (checked == 0) {
                    var msg = 'The {{ __('backend/cruise-free-service.coupon') }} field is required.';
                    addErrorValidateForm($('#validate_coupon_id'), msg);
                }

                var checked = $("input[name='free_service[]']:checked").length;
                if (checked == 0) {
                    var msg = 'The {{ __('backend/cruise-free-service.free-service') }} field is required.';
                    addErrorValidateForm($('#validate_free_service_id'), msg);
                }

                var selected = $("#cruise_id").val().length;
                if (selected == 0) {
                    var msg = 'The {{ __('backend/cruise-promotion.cruise') }} field is required.';
                    addErrorValidateForm($('#validate_cruise_id'), msg);
                }

                if ($('#cruise_id').val().includes("-1")) {
                    var allCruises = [];
                    $.each($('#cruise_id option'), function(i,e) {
                        var val = $(e).attr('value');
                        if (val != -1) allCruises.push(val);
                    });
                    $('#cruise_id').val(allCruises);
                }

                if ($('#from').val() != '' && $('#to').val() != '') {
                    var partsFrom = $('#from').val().split('/');
                    var partsTo = $('#to').val().split('/');

                    var fromDate = new Date(partsFrom[2], partsFrom[1] - 1, partsFrom[0]);
                    var toDate = new Date(partsTo[2], partsTo[1] - 1, partsTo[0]);

                    if (fromDate > toDate) {
                        var msg = 'The to date field must be greater than the from date field.';
                        addErrorValidateForm($('#validate_to'), msg);
                    }
                }

                validateForm(e);
            });

            var today = new Date();
            var dd = String(today.getDate()).padStart(2, '0');
            var mm = String(today.getMonth() + 1).padStart(2, '0');
            var yyyy = today.getFullYear();
            var current_time = String(today.getHours()).padStart(2, '0') + ":" + String(today.getMinutes()).padStart(2, '0') + ":" + String(today.getSeconds()).padStart(2, '0');
            today = dd + '/' + mm + '/' + yyyy;

            function getYesterdaysDate() {
                var date = new Date();
                date.setDate(date.getDate()-1);
                return date;
            }

            var from = $('#from').pickadate({
                today: '',
                clear: '',
                close: '',
                format: 'dd/mm/yyyy',
                disable: [
                    { from: -10000, to: getYesterdaysDate() }
                ]
            });
            if (from.val() == '') {
                from.val(today);
            }

            var to = $('#to').pickadate({
                today: '',
                clear: '',
                close: '',
                format: 'dd/mm/yyyy',
                disable: [
                    { from: -10000, to: getYesterdaysDate() }
                ]
            });
            if (to.val() == '') {
                to.val(today);
            }
        });
    </script>
@endpush

resources/views/backend/cruise-free-service/index.blade.php
@extends('layouts.admin')

@section('title', __('backend.cruise-free-service'))

@push('after-styles')
    {{ Html::style('xtreme-admin/css/datatables.min.css') }}
@endpush

@section('content')
    {{ Breadcrumbs::render('cruise-free-service') }}

    <div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-6"><h3>{{ __('backend.cruise-free-service') }}</h3></div>
                <div class="col-6 text-right">
                    <a href="{{ route('backend.cruise-free-service.create') }}" class="btn btn-primary">{{ __('web.create') }}</a>
                </div>
            </div>

            <div class="table-responsive mt-3">
                <table id="the_table" class="table table-striped table-bordered display" style="width:100%">
                    <thead>
                    <tr>
                        <th>{{ __('No.') }}</th>
                        <th>{{ __('backend/cruise-free-service.cruise') }}</th>
                        <th>{{ __('backend/cruise-free-service.free-service') }}</th>
                        <th>{{ __('backend/cruise-free-service.from') }}</th>
                        <th>{{ __('backend/cruise-free-service.to') }}</th>
                        <th>{{ __('web.action') }}</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>

        </div>
    </div>
    </div>
@endsection

@push('after-scripts')
    {!! Html::script('xtreme-admin/js/datatables.min.js') !!}

    <script>
        $(function () {
            "use strict";

            var table = $('#the_table').DataTable({
                dom: '<"pull-left"f><"pull-right"l>tip',
                processing: false,
                language: {
                    url: "{{ url('xtreme-admin/js/datatablelanguage.json') }}"
                },
                serverSide: true,
                ajax: "{{ route('backend.cruise-free-service.index') }}?ajax",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', width: '30px', className: 'text-center', searchable: false},
                    {data: 'cruise', name: 'cruise'},
                    {data: 'free-service', name: 'free-service'},
                    {data: 'from', name: 'from', searchable: false, className: 'text-center'},
                    {data: 'to', name: 'to', searchable: false, className: 'text-center'},
                    {data: 'action', name: 'action', orderable: false, className: 'text-center', searchable: false, width: '150px'},
                ]
            }).on('error.dt', function (e, settings, techNote, message) {
                console.log(e);
            });

            setupBtDeleteDatatable(table, '{{ __('backend.cruise-free-service') }}');
        });
    </script>
@endpush